### ISSUE TITLE
TypeScript and playground

### ISSUE THREAD

**Issue by hatemhosny** [mahyoussef/ultimate-design-patterns#1]
السلام عليكم ورحمة الله وبركاته 

A great course. 
Thank you for making that available and for enriching Arabic content.

I have very little knowledge in Java, however I was perfectly comfortable following along.
I am thinking of providing a TypeScript version (which I'm a lot more comfortable with) for the modules I learn. 
I think of these benefits:
- I find it a good chance for me to apply, rather than just keep watching.
- I can get better in Java if I know the TypeScript counterpart.
- A lot more people (who, like me, know JS/TS better) can follow the course better if they can find TypeScript code.
- We can easily run TypeScript code in online code playgrounds and get immediate feedback.
- This will also motivate me to continue the course till the end (PS. I'm lazy!)

This is the observer pattern translated to TypeScript:
https://github.com/hatemhosny/ultimate-design-patterns/tree/typescript/typescript/observer

You can then run the code in [LiveCodes](https://livecodes.io), like that:
Observer pattern: [run in LiveCodes](https://livecodes.io/?console&x=https://github.com/hatemhosny/ultimate-design-patterns/blob/typescript/typescript/observer/_observer.ts)

(LiveCodes is an [open-source](https://github.com/live-codes/livecodes) client-side code playground that I maintain, which supports TypeScript and [80+ other languages/frameworks](https://livecodes.io/docs/why). See [docs](https://livecodes.io/docs/) - [starter templates](https://livecodes.io?new))

You can also run the code locally using something like [`ts-node`](https://www.npmjs.com/package/ts-node) (if you have npm globally installed) using the command:
```shell
npx ts-node ./typescript/observer/index.ts
```

### Notes

Instead of translating statement to statement, I used conventions common in TypeScript,. These are some examples:
-  String literal unions instead of enums

```ts
// union type
type EventType = "NEW_PRODUCT" | "NEW_OFFER" | "JOB_OPENING";

// instead of enum
enum EventType {
  NEW_PRODUCT,
  NEW_OFFER,
  JOB_OPENING,
}
```

- [parameter properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties) shorthand

```ts

class Offer {
  constructor(private message: string) {}

  getMessage() {
    return this.message;
  }
}

// instead of
class Offer {
  private message: string;

  constructor(message: string) {
    this.message = message;
  }

  getMessage() {
    return this.message;
  }
}
```

- kebab case for file names instead of Pascal case (Only file names. Class name are the same)
  (e.g. `shipping-company.ts` instead of `ShippingCompany.ts`)

- The entry point and usage example is found in [`index.ts`](https://github.com/hatemhosny/ultimate-design-patterns/blob/typescript/typescript/observer/index.ts) (similar to the code in `main`)
- I have collected all code in one file ([`_observer.ts`](https://github.com/hatemhosny/ultimate-design-patterns/blob/typescript/typescript/observer/_observer.ts)) for a general overview and for easy loading in LiveCodes.

I would appreciate if you can also provide the code in `main` (for each pattern) in the repo (I had to get it from the video).

You may also want to provide links to UML diagrams as code:
e.g. this [UML diagram](https://mermaid.live/view#pako:eNqdk01ugzAQha9ieUVaygFYdJMQKZUaUEjVRYgqxzapVbCRfypFUXKLHqan6hWKDYK0gS66AcR7b-abkX2EWBAKQwgALpBSM4b2EpUZByDmBeP0Eck3qqsCYQqC4B5E75Tr9aGiw5abIACp2Sks2Y7KcU8iBTFYjxviPG_yfTXX_0Hs5owTqw2HQ3AHVJdRX58fYEWxkOTcofsXRTfb83idqqF0RVrizXbcLiyzMzv6cettT-gNUk3Gk4b_P4sIacfw2vffZjeG556TZt9dx9qyjJ5fklU8e5qu_SEtns-j1ZUSJ9HyJYnTxXoRL1O_KdvT285caJYfPKUl4_u2cctr18xRSe2SG_2XWEmGncpN2Z5AN6KdweolVQrtf-St3h2r4QYX8jDe1CgtyrF4r16nAfRhLZWIkfoaHh0w1K-0pBkM609Cc2QKncGMn2orMlqkB45hqKWhPjQVQZq217b5efoG_VldVg) uses [mermaid](https://mermaid.js.org/) ([load in editor](https://mermaid.live/edit#pako:eNqdk01ugzAQha9ieUVaygFYdJMQKZUaUEjVRYgqxzapVbCRfypFUXKLHqan6hWKDYK0gS66wUjvvZlvRvYRYkEoDCEAuEBKzRjaS1RmHICYF4zTRyTfqK4KhCkIgnsQvVOu14eKDltuggCkZqewZDsqxz2JFMRgPW6I87zJ99Vc_wexmzNOrDYcDsEdUF1GfX1-gBXFQpJzh-5fFN1sz-N1qobSFWmJN9txu7DMzuzox623PaE3SDUZTxr-_ywipB3Da8-_zW4Mz30nzb67jrVlGT2_JKt49jRd-0NaPJ9HqyslTqLlSxKni_UiXqZ-U7ant5250Cw_eEpLxvdt45bXrpmjktolN_ovsZIMO5Wbsr2BbkQ7g9VLqhTa_8hbvbtWww0u5GG8qVFalGPxXr1OA-jDWioRI_UzPDpgqF9pSTMY1r-E5sgUOoMZP9VWZLRIDxzDUEtDfWgqgjRtny0Mc1QoevoGWmhdoQ))

If you agree to the general idea, I'll open a PR to merge the code back in your repo.
Please let me know what you think.

**Comment by mahyoussef** [comment]
اللهم بارك يا حاتم , ما شاء الله عليك شغل عالي وفاخر بجد 😍
This is a really awesome contribution from your side, I loved the way you wrote a clean code + the way that you provided a UML as a Code was very elegant. 

Please feel free to open a PR so you can motivate others to start writing into other languages and motivate typescript users to get going with type script. 

Thanks a lot for your nice words in the beginning and I really hope the rest of the course be more exciting to you !

**Comment by hatemhosny** [comment]
ربنا يكرمك، كورس حلو فعلا ❤️

I will open a PR with the current TypeScript implementation of the observer pattern and hopefully follow up with more PRs for other patterns as I advance through the course.

I hope this motivates others to provide implementations for other languages.

Please note that [LiveCodes playground](https://livecodes.io/?new) supports other languages like Python, Go, C++, PHP, Ruby and many others (unfortunately, Java is not "yet" supported). So other developers may want to use it to showcase the implementation in other languages.
